name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  ACR_NAME: Somtodoacr
  ACR_LOGIN_SERVER: somtodoacr.azurecr.io
  IMAGE_NAME: todo-app

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: "2763f7b2-eaf9-4ef4-8935-ee21538622d2"
          tenant-id: "9c0e74bf-63ad-4d83-802c-30dfa888859a"
          subscription-id: "9435f968-f680-4062-9594-8bb4396ee93c"

      - name: Login to Azure Container Registry
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
